[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"
